"""Canonical configuration serialization and content hashing."""

from __future__ import annotations

import hashlib
import json
import math
from collections.abc import Mapping
from enum import Enum
from pathlib import Path
from typing import Any, Final

from pydantic import BaseModel

from hybrid_v2x_rl.core.errors import ConfigurationError

PROJECT_ROOT_TOKEN: Final = "${PROJECT_ROOT}"

HASH_EXCLUDED_PATHS: Final[tuple[tuple[str, ...], ...]] = (("environment", "splits"),)
"""Configuration paths that record bookkeeping rather than physics.

``config_hash`` answers one question: were two artifacts produced under the
same experimental conditions?  A field belongs here when changing it cannot
change any generated byte.

``environment.splits`` names which trace identifiers are held out for
validation and test.  Split membership is consumed at training and evaluation
time; it is not read by any generator.  Adding a replicate to the test list
therefore moves no vehicle, yet without this exclusion it would change the
digest and strand every previously published trace under a stale hash.

The excluded values are not lost.  ``canonical_json`` still serializes them in
full, every trace stores its complete ``resolved_config.yaml``, and the
campaign manifest records the split map explicitly.
"""

# Per-artifact-class digests answer whether a producer's inputs agree.  The
# exclusion lists are fail-safe: an unreviewed new field remains in a scope and
# can cause only a visible, wasteful incompatibility rather than unsafe reuse.
# ``mobility`` is legacy provenance. ``mobility_trace`` is the replay contract
# and deliberately retains training.root_seed while excluding every currently
# known optimizer field.
_TRAINING_EXCEPT_ROOT_SEED: Final[tuple[tuple[str, ...], ...]] = (
    ("training", "algorithm"),
    ("training", "policy_seeds"),
    ("training", "total_transitions_per_seed"),
    ("training", "architecture"),
    ("training", "rollout_packets"),
    ("training", "minibatch_size"),
    ("training", "update_epochs"),
    ("training", "learning_rate"),
    ("training", "gamma"),
    ("training", "gae_lambda"),
    ("training", "clip_ratio"),
    ("training", "entropy_coefficient"),
    ("training", "cost_signal"),
    ("training", "curriculum"),
    ("training", "density_multipliers"),
    ("training", "checkpoint_selection"),
    ("training", "normalize_observations_on_training_only"),
)

HASH_SCOPES: Final[dict[str, tuple[tuple[str, ...], ...]]] = {
    "mobility": (
        ("observation",),
        ("rf",),
        ("vlc",),
        ("service",),
        ("cost",),
        ("evaluation",),
    ),
    # Replay compatibility for immutable mobility traces.  Unlike the legacy
    # ``mobility`` provenance scope above, this excludes every optimizer field
    # while retaining training.root_seed, the only training value read by the
    # trace generator.  Existing artifacts can be checked by hashing their
    # integrity-protected resolved_config.yaml under this current scope.
    "mobility_trace": (
        ("project",),
        ("paths",),
        ("observation",),
        ("rf",),
        ("vlc",),
        ("service",),
        ("cost",),
        ("evaluation",),
        ("environment",),
        *_TRAINING_EXCEPT_ROOT_SEED,
    ),
    # Environment/audit compatibility keeps all policy-visible and physical
    # state definitions while excluding optimizer and reporting choices.
    "policy_environment": (
        ("project",),
        ("paths",),
        ("evaluation",),
        *_TRAINING_EXCEPT_ROOT_SEED,
    ),
}


def _project_root(value: BaseModel) -> Path | None:
    """Return a resolved project root when ``value`` is a project config."""

    paths = getattr(value, "paths", None)
    root = getattr(paths, "project_root", None)
    return root.resolve(strict=False) if isinstance(root, Path) else None


def _canonical_path(value: Path, project_root: Path | None) -> str:
    """Keep in-project paths portable while preserving external absolute paths."""

    if project_root is None:
        return value.as_posix()
    resolved = value.resolve(strict=False)
    try:
        relative = resolved.relative_to(project_root)
    except ValueError:
        return resolved.as_posix()
    if relative == Path("."):
        return PROJECT_ROOT_TOKEN
    return f"{PROJECT_ROOT_TOKEN}/{relative.as_posix()}"


def _canonicalize(value: Any, *, project_root: Path | None = None) -> Any:
    """Convert supported values into a deterministic JSON-compatible tree."""

    if isinstance(value, BaseModel):
        inferred_root = _project_root(value)
        return _canonicalize(
            value.model_dump(mode="python", by_alias=True, exclude_none=False),
            project_root=inferred_root if inferred_root is not None else project_root,
        )
    if isinstance(value, Path):
        return _canonical_path(value, project_root)
    if isinstance(value, Enum):
        return _canonicalize(value.value, project_root=project_root)
    if isinstance(value, Mapping):
        canonical: dict[str, Any] = {}
        for key, item in value.items():
            if not isinstance(key, (str, int, float, bool)):
                raise ConfigurationError(f"configuration map key is not JSON-compatible: {key!r}")
            key_text = str(key)
            if key_text in canonical:
                raise ConfigurationError(
                    f"configuration keys collide after serialization: {key_text!r}"
                )
            canonical[key_text] = _canonicalize(item, project_root=project_root)
        return {key: canonical[key] for key in sorted(canonical)}
    if isinstance(value, (list, tuple)):
        return [_canonicalize(item, project_root=project_root) for item in value]
    if isinstance(value, (set, frozenset)):
        items = [_canonicalize(item, project_root=project_root) for item in value]
        return sorted(
            items,
            key=lambda item: json.dumps(
                item,
                sort_keys=True,
                separators=(",", ":"),
                ensure_ascii=False,
                allow_nan=False,
            ),
        )
    if isinstance(value, float):
        if not math.isfinite(value):
            raise ConfigurationError("configuration contains a non-finite floating-point value")
        # JSON distinguishes -0.0 from 0.0 although the configurations do not.
        return 0.0 if value == 0.0 else value
    if value is None or isinstance(value, (str, int, bool)):
        return value
    raise ConfigurationError(
        f"configuration contains unsupported value type {type(value).__name__}"
    )


def canonical_data(config: BaseModel | Mapping[str, Any]) -> dict[str, Any]:
    """Return a canonical mapping suitable for serialization and comparison."""

    result = _canonicalize(config)
    if not isinstance(result, dict):
        raise ConfigurationError("top-level configuration must be a mapping")
    return result


def _dumps(data: Any) -> str:
    return json.dumps(
        data,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    )


def _without_path(data: dict[str, Any], path: tuple[str, ...]) -> dict[str, Any]:
    """Return ``data`` with ``path`` removed, leaving the input untouched.

    A path that is absent, or whose prefix is not a mapping, is a no-op: the
    exclusion list describes the project configuration, and hashing an
    unrelated mapping must not fail because that mapping is shaped differently.
    """

    head, *rest = path
    if head not in data:
        return data
    if not rest:
        return {key: value for key, value in data.items() if key != head}
    branch = data[head]
    if not isinstance(branch, dict):
        return data
    return {**data, head: _without_path(branch, tuple(rest))}


def canonical_json(config: BaseModel | Mapping[str, Any]) -> str:
    """Serialize a configuration with stable ordering and no insignificant space.

    This is the complete serialization, including the fields ``config_hash``
    excludes from its digest.
    """

    return _dumps(canonical_data(config))


def hashed_data(config: BaseModel | Mapping[str, Any]) -> dict[str, Any]:
    """Return the canonical mapping that ``config_hash`` actually digests."""

    data = canonical_data(config)
    for path in HASH_EXCLUDED_PATHS:
        data = _without_path(data, path)
    return data


def config_hash(config: BaseModel | Mapping[str, Any]) -> str:
    """Return the lowercase SHA-256 digest of the physics-bearing configuration.

    Fields listed in ``HASH_EXCLUDED_PATHS`` are omitted so that bookkeeping
    edits do not invalidate artifacts they cannot have affected.

    This is the *run* digest: it answers whether two runs happened under the
    same conditions.  For "may this artifact be reused?", prefer
    :func:`scope_hash`, which asks only about the configuration the artifact's
    producer can read.
    """

    payload = _dumps(hashed_data(config)).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def scoped_data(config: BaseModel | Mapping[str, Any], scope: str) -> dict[str, Any]:
    """Return the canonical mapping that :func:`scope_hash` digests."""

    if scope not in HASH_SCOPES:
        raise ConfigurationError(
            f"unknown configuration hash scope {scope!r}; "
            f"known scopes: {', '.join(sorted(HASH_SCOPES))}"
        )
    data = hashed_data(config)
    for path in HASH_SCOPES[scope]:
        data = _without_path(data, path)
    return data


def scope_hash(config: BaseModel | Mapping[str, Any], scope: str) -> str:
    """Digest of only the configuration a ``scope``'s producer can read.

    Two artifacts of the same scope that agree here were produced under
    identical *relevant* conditions, whatever else changed around them.  That
    is the question worth asking of a stored artifact, and asking it of the
    global digest instead is what turns an unrelated edit into hours of
    recomputation for bytes that could not differ.
    """

    payload = _dumps(scoped_data(config, scope)).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()
